### ISSUE TITLE
Move the Showcase application to the new backend system

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rhdh#834]
## Goal

Move the Showcase application to the new backend system.

This would be a prerequisite to making the usage of backend dynamic plugins simpler, especially for external backend dynamic plugins, since dynamic plugins on the new backend system do not require adding entrypoints in the source manually (which they require on the old backend system).

## Acceptance criteria

- [ ] Have all the tests pass and all the features work correctly.

## Requirements

- [ ] Test plan
- [ ] Documentation

## Issues in Epic

- [ ] Check that all required plugins (static and dynamic) have been made compatible with the new backend system
  - [x] [Contribute new backend support to plugins in the `backstage-plugins` repo.](https://github.com/janus-idp/backstage-plugins/issues/1062)
  - [ ] [Validate dynamic plugin wrappers against new backend system](https://github.com/janus-idp/backstage-showcase/issues/883)
- [ ] [Add support for the new backend system to the RBAC backend plugin](https://github.com/janus-idp/backstage-plugins/issues/1063)
- [ ] [Switch the Showcase backend app to the new backend system](https://github.com/janus-idp/backstage-showcase/issues/884)
 
## Notes

**Additional context**
Add any other context or screenshots about the epic here.

**Comment by coreydaley** [comment]
@davidfestal Hmmm, I think this has been done already?
