### ISSUE TITLE
Finalize the dynamic backend plugin support in upstream backstage

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rhdh#835]
## Goal

Finalize the dynamic backend plugin support in upstream backstage.

Since in upstream Backstage there is not plan to promote dynamic plugins on the old backend, ideally this EPIC would depend on EPIC #834.

## Acceptance criteria

- [ ] Have the showcase support dynamic backend plugins by simply importing upstream backstage packages, without specific showcase logic or workarounds. 

## Requirements

- [ ] Test plan
- [ ] Documentation

## Issues in Epic

- [x] [Make the Janus CLI work on backstage upstream plugins](https://github.com/janus-idp/backstage-plugins/issues/1051)
- [x] Support new backend system default exports in the upstream `backend-plugin-manager` (PR https://github.com/backstage/backstage/pull/21612)
- [x] Fix in upstream the limitations encountered on the Showcase and fixed through workarounds
  - [x] https://github.com/backstage/backstage/issues/21631 (PR: https://github.com/backstage/backstage/pull/21632)
  - [x] https://github.com/backstage/backstage/issues/21768 (PR: https://github.com/backstage/backstage/pull/22267)
- [x] Followups on the [initial RFC PR](https://github.com/backstage/backstage/pull/18862), to make the package public (it's private for now), and have it published in NPMJS in the `@backstage` organization:
  - [x] Better follow Backstage API Design style guidelines (PR: https://github.com/backstage/backstage/pull/21764)
  - [x] [Rename package to a more precise name](https://github.com/backstage/backstage/pull/21764#issuecomment-1843257581)
- [x] Wait for a new Backstage release with the renamed `backstage -plugin-manager` published to NPM.
- [x] Update the Showcase to bump the backstage dependencies to this backstage release and use the lastest, renamed dynamic plugins service package.

## Notes

**Additional context**
Add any other context or screenshots about the epic here.
